name: rqlite
version: 3.9.0+git
summary: The lightweight, distributed relational database built on SQLite
description: |
  rqlite provides a lightweight, distributed relational database.

  rqlite is written in Go and uses Raft to achieve consensus across all
  the instances of the SQLite databases. rqlite ensures that every change
  made to the system is made to a quorum of SQLite databases, or none at
  all. It also gracefully handles leader elections, and tolerates failures
  of machines, including the leader.
confinement: strict
grade: stable


apps:
  rqlite:
    command: bin/rqlite
    plugs: [ home, network-bind ]
  rqlited:
    command: bin/rqlited
    plugs: [ home, network-bind ]
  launch:
    daemon: forking
    command: bin/snap-launch.py start
    stop-command: bin/snap-launch.py stop
    plugs: [ network-bind ]

parts:
  rqlite:
    plugin: go
    source: https://github.com/rqlite/rqlite.git
  scripts:
    plugin: dump
    source: scripts
